# fly.toml app configuration file generated for 5e-game-master on 2026-06-17T21:07:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '5e-game-master'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'campaigns_data'
  destination = '/data/campaigns'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
